width: 300
height: 300
device: "GPU|CPU"
weights: "data/models/mask_rcnn_inception_v2_coco/frozen_inference_graph.pb"
threshold: 0.4
per_process_gpu_memory_fraction: 0.0
labels: {1: "person"}
log_device_placemenent: false
